# This is for the web version of the video editor (when hosted with Akeno).
# For the desktop version, launch via electron (electron .)

server {
    domains: "video-editor.{localhost, lstv.space}";
}

# location("/", "index.html") alias: "src-index.html";

ls version: beta;

browserSupport {
    chrome: 134;
    firefox: 130;
}